kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-indicator-controller
  namespace: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus-indicator-controller
    namespace: prometheus # TODO: don't bind to prometheus namespace
roleRef:
  kind: ClusterRole
  name: prometheus-indicator-controller
  apiGroup: rbac.authorization.k8s.io
