kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-indicator-controller
  namespace: grafana
subjects:
  - kind: ServiceAccount
    name: grafana-indicator-controller
    namespace: grafana # TODO: don't bind to grafana namespace
roleRef:
  kind: ClusterRole
  name: grafana-indicator-controller
  apiGroup: rbac.authorization.k8s.io
