apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: indicatordocuments.apps.pivotal.io
spec:
  group: apps.pivotal.io
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: indicatordocuments
    singular: indicatordocument
    kind: IndicatorDocument
    shortNames:
    - id
    - indicator
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - product
          properties:
            product:
              required:
              - name
              - version
            indicators:
              type: array
              items:
                required:
                - name
                - promql
                properties:
                  documentation:
                    type: object
                  thresholds:
                    type: array
                    items:
                      required:
                      - level
                      properties:
                        gte:
                          type: number
                        gt:
                          type: number
                        eq:
                          type: number
                        neq:
                          type: number
                        lt:
                          type: number
                        lte:
                          type: number
